package org.twelve.outline.common;

public final class Constants {
    public static final String MODULE_STATEMENT = "module_statement";
    public static final String IMPORT_STATEMENT = "import_statement";
    public static final String EXPORT_STATEMENT = "export_statement";
    public static final String IMPORT = "Import";
    public static final String EXPORT = "Export";
    public static final String DOT = "Dot";
    public static final String AS = "As";
    public static final String COMMA = "COMMA";
    public static final String FROM = "From";
    public static final String SEMICOLON = "SEMICOLON";
    public static final String VARIABLE_DECLARATOR = "variable_declarator";
    public static final String ROOT = "root";
    public static final String ID = "ID";
    public static final String COLON = "COLON";
    public static final String EQUAL = "EQUAL";
    public static final String STRING = "STRING";
    public static final String DOUBLE = "Double";
    public static final String NUMBER = "NUMBER";
    public static final String COLON_ = ":";
    public static final String ID_TYPE = ":ID";
    public static final String INT_TYPE = ":Int_Type";
    public static final String DOUBLE_TYPE = ":Double_Type";
    public static final String FUNCTION = "lambda";
    public static final String NUMERIC_EXPRESSION = "numeric_expression";
    public static final String BLOCK = "block";
    public static final String ENTITY = "entity";
    public static final String PROPERTY_ASSIGNMENT = "property_assignment";
    public static final String VAR = "Var";
    public static final String LET = "Let";
    public static final String FACTOR_EXPRESSION = "factor_expression";
    public static final String THIS = "This";
    public static final String MEMBER_ACCESSOR = "entity_member_accessor";
    public static final String FUNCTION_CALL = "function_call";
    public static final String ARRAY_MAP_ACCESSOR = "array_map_accessor";
    public static final String TUPLE = "tuple";
    public static final String ARGUMENT = "argument";
    public static final String TUPLE_TYPE = "tuple_type";
    public static final String QUESTION_TYPE = "QUESTION";
}
